# Generated by Django 5.0.2 on 2024-04-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comingsoon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediashuttletraining',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='mediashuttletraining',
            name='training',
            field=models.CharField(choices=[('Training', [('Morning', 'Afternoon')])], default='1', max_length=20),
        ),
    ]
