# Generated by Django 5.0.2 on 2024-04-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comingsoon', '0002_rename_name_mediashuttletraining_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediashuttletraining',
            name='training',
            field=models.CharField(choices=[('Morning', 'Afternoon')], default='1', max_length=20),
        ),
    ]
