# Generated by Django 5.0.2 on 2024-04-04 09:10

import comingsoon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comingsoon', '0003_alter_mediashuttletraining_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediashuttletraining',
            name='dep_time',
            field=models.TimeField(blank=True, default=comingsoon.models.default_start_time),
        ),
        migrations.AlterField(
            model_name='mediashuttletraining',
            name='training',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], default='0', max_length=20),
        ),
    ]
