# Generated by Django 5.0.2 on 2024-04-04 09:13

import comingsoon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comingsoon', '0004_mediashuttletraining_dep_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediashuttletraining',
            name='arr_time',
            field=models.TimeField(blank=True, default=comingsoon.models.default_start_time),
        ),
        migrations.AddField(
            model_name='mediashuttletraining',
            name='travel_time',
            field=models.IntegerField(default=1),
        ),
    ]
