# Generated by Django 5.0.2 on 2024-04-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comingsoon', '0005_mediashuttletraining_arr_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediashuttletraining',
            name='number_of_staff',
            field=models.IntegerField(default=1),
        ),
    ]
