# Generated by Django 5.0.2 on 2024-04-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comingsoon', '0007_mediashuttletraining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediashuttletraining',
            name='filter_variable',
            field=models.CharField(default='stv', max_length=5),
        ),
    ]
