# Generated by Django 5.0.2 on 2024-04-04 10:37

import comingsoon.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comingsoon', '0008_mediashuttletraining_filter_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaShuttleCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('filter_variable', models.CharField(default='stv', max_length=5)),
                ('training', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], default='0', max_length=20)),
                ('dep_time', models.TimeField(blank=True, default=comingsoon.models.default_start_time)),
                ('travel_time', models.IntegerField(default=1)),
                ('arr_time', models.TimeField(blank=True, default=comingsoon.models.default_start_time)),
                ('number_of_staff', models.IntegerField(default=1)),
            ],
        ),
    ]
