# Generated by Django 5.0.2 on 2024-04-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comingsoon', '0011_pdf_alter_mediashuttlecompetition_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(upload_to='comingsoon/media/pdfs/'),
        ),
    ]
