# Generated by Django 5.0.2 on 2024-04-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comingsoon', '0012_alter_pdf_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='pdf_explanation',
            field=models.CharField(blank=True, help_text='Enter an explanation for the associated PDF file.', max_length=200, verbose_name='Explanation for PDFs'),
        ),
    ]
