# Generated by Django 5.0.2 on 2024-04-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comingsoon', '0013_pdf_pdf_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='title',
            field=models.CharField(blank=True, help_text='Enter an title for the associated PDF file.', max_length=200, verbose_name='Title for PDFs'),
        ),
    ]
