# Generated by Django 5.0.2 on 2024-04-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comingsoon', '0014_alter_pdf_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaShuttleCompetition',
        ),
        migrations.DeleteModel(
            name='MediaShuttleTraining',
        ),
    ]
